'use client';

import type { OrderDetail } from '@/hooks/use-orders';
import { formatEtb } from '@/lib/utils';

export function InvoiceDocument({ order, isSeller }: { order: OrderDetail; isSeller: boolean }) {
  const payment = order.payments[0];
  const party = isSeller ? order.client : order.seller;
  return (
    <article
      className="invoice-export-document bg-white p-10 font-sans text-black"
      style={{ width: '794px', minHeight: '1123px' }}
    >
      <header className="flex items-start justify-between border-b-2 border-violet-600 pb-6">
        <div>
          <div className="text-2xl font-black tracking-tight text-violet-700">APEX-WORK</div>
          <div className="mt-1 text-xs text-neutral-500">Ethiopia&apos;s freelance marketplace</div>
        </div>
        <div className="text-right">
          <h1 className="text-2xl font-extrabold">
            {isSeller ? 'Earnings receipt' : 'Payment receipt'}
          </h1>
          <p className="mt-1 text-xs text-neutral-500">#{order.orderNumber}</p>
          <p className="text-xs text-neutral-500">
            {new Date(order.createdAt).toLocaleDateString()}
          </p>
        </div>
      </header>
      <section className="mt-8 grid grid-cols-2 gap-8 text-sm">
        <div>
          <div className="text-[10px] font-bold uppercase tracking-widest text-neutral-400">
            {isSeller ? 'Client' : 'Freelancer'}
          </div>
          <div className="mt-2 font-bold">{party.fullName}</div>
          <div className="text-xs text-neutral-500">@{party.username}</div>
        </div>
        <div className="text-right">
          <div className="text-[10px] font-bold uppercase tracking-widest text-neutral-400">
            Status
          </div>
          <div className="mt-2 font-bold text-emerald-600">{order.status}</div>
          <div className="text-xs text-neutral-500">
            {payment?.provider ?? 'Apex-Work escrow'}
            {payment?.method ? ` · ${payment.method}` : ''}
          </div>
        </div>
      </section>
      <section className="mt-10 overflow-hidden rounded-xl border border-neutral-200">
        <div className="grid grid-cols-[1fr_auto] border-b border-neutral-200 bg-neutral-50 px-4 py-3 text-xs font-bold uppercase tracking-wide">
          <span>Description</span>
          <span>Amount</span>
        </div>
        <div className="grid grid-cols-[1fr_auto] gap-4 px-4 py-5 text-sm">
          <div>
            <div className="font-bold">{order.title}</div>
            <div className="mt-1 text-xs text-neutral-500">Apex-Work protected project payment</div>
          </div>
          <div className="font-bold">{formatEtb(order.amountEtb)}</div>
        </div>
      </section>
      <section className="ml-auto mt-6 w-72 space-y-2 text-sm">
        <div className="flex justify-between">
          <span className="text-neutral-500">Order total</span>
          <b>{formatEtb(order.amountEtb)}</b>
        </div>
        {isSeller && (
          <>
            <div className="flex justify-between text-neutral-500">
              <span>Platform fee</span>
              <span>− {formatEtb(order.platformFeeEtb)}</span>
            </div>
            <div className="border-t border-neutral-300 pt-2">
              <div className="flex justify-between text-base">
                <b>Your net</b>
                <b className="text-emerald-600">{formatEtb(order.sellerNetEtb)}</b>
              </div>
            </div>
          </>
        )}
      </section>
      <footer className="mt-20 border-t border-neutral-200 pt-4 text-xs text-neutral-500">
        <p>
          Funds are handled through Apex-Work escrow and Chapa. Keep this receipt for your records.
        </p>
        <p className="mt-1">
          Generated by Apex Resume &amp; Work Studio · apex-work-gold.vercel.app
        </p>
      </footer>
    </article>
  );
}
