/**
 * Downloadable receipts & monthly earnings statements.
 *
 * Pure, dependency-free builders that turn order/earnings data into
 * self-contained printable HTML (inline styles only — no external CSS/fonts so
 * a downloaded file renders identically offline). Unit-testable without a DB.
 */

function esc(v: string | number | null | undefined): string {
  return String(v ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const etb = (n: number): string => `${Math.round(n).toLocaleString('en-US')} ETB`;

const BASE = `
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#111;background:#fff;padding:32px;max-width:720px;margin:0 auto}
  .brand{display:flex;align-items:center;gap:8px;font-weight:800;font-size:18px;color:#4f46e5}
  .brand .dot{width:12px;height:12px;border-radius:4px;background:#4f46e5}
  .muted{color:#6b7280}
  .row{display:flex;justify-content:space-between;padding:10px 0;border-bottom:1px solid #e5e7eb}
  .row b{font-weight:700}
  .totals{margin-top:20px;border-radius:12px;background:#f9fafb;padding:16px;border:1px solid #e5e7eb}
  .h1{font-size:24px;font-weight:800;margin:18px 0 4px}
  .sub{color:#6b7280;font-size:13px;margin-bottom:24px}
  .grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}
  .card{border:1px solid #e5e7eb;border-radius:12px;padding:14px}
  .card .k{font-size:11px;color:#6b7280;text-transform:uppercase;letter-spacing:.04em}
  table{width:100%;border-collapse:collapse;margin-top:12px;font-size:13px}
  th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.04em;color:#6b7280;padding:8px 6px;border-bottom:1px solid #e5e7eb}
  td{padding:9px 6px;border-bottom:1px solid #f3f4f6}
  td.num,th.num{text-align:right}
  .footer{margin-top:28px;font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb;padding-top:12px;text-align:center}
</style>
`;

function doc(title: string, body: string): string {
  return `<!doctype html><html lang="en"><head><title>${esc(title)}</title>${BASE}</head><body>${body}<div class="footer">Generated by Apex-Work · ${esc(new Date().toISOString().slice(0, 10))} · This document is a record for your records.</div></body></html>`;
}

export interface ReceiptData {
  orderNumber: string;
  title: string;
  createdAt: string | Date;
  status: string;
  clientName: string;
  sellerName: string;
  amountEtb: number;
  platformFeeEtb: number;
  sellerNetEtb: number;
  paymentMethod?: string | null;
  paymentStatus?: string | null;
  providerRef?: string | null;
}

/** Build a standalone, printable HTML receipt for a single order. */
export function buildOrderReceipt(r: ReceiptData): { html: string; filename: string } {
  const date = new Date(r.createdAt);
  const dt = Number.isNaN(date.getTime()) ? String(r.createdAt) : date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const html = doc(`Apex-Work receipt ${r.orderNumber}`, `
    <div class="brand"><span class="dot"></span>Apex-Work</div>
    <h1 class="h1">Payment receipt</h1>
    <div class="sub">Receipt ${esc(r.orderNumber)} · ${esc(dt)}</div>
    <div class="grid">
      <div class="card"><div class="k">Order</div><div class="h1" style="font-size:15px;margin-top:6px">${esc(r.title)}</div></div>
      <div class="card"><div class="k">Status</div><div style="margin-top:6px;font-weight:700">${esc(r.status)}</div></div>
      <div class="card"><div class="k">Client</div><div style="margin-top:6px">${esc(r.clientName)}</div></div>
      <div class="card"><div class="k">Freelancer</div><div style="margin-top:6px">${esc(r.sellerName)}</div></div>
    </div>
    <div class="totals">
      <div class="row"><span>Order total</span><b>${etb(r.amountEtb)}</b></div>
      <div class="row"><span class="muted">Platform fee</span><span class="muted">− ${etb(r.platformFeeEtb)}</span></div>
      <div class="row" style="border-bottom:none"><span>Paid to freelancer</span><b>${etb(r.sellerNetEtb)}</b></div>
    </div>
    <div class="card" style="margin-top:16px">
      <div class="k">Payment</div>
      <div style="margin-top:6px"><b>${esc(r.paymentMethod ?? 'Chapa')}</b> · ${esc(r.paymentStatus ?? '')}</div>
      ${r.providerRef ? `<div class="muted" style="margin-top:4px;font-size:12px">Ref: ${esc(r.providerRef)}</div>` : ''}
    </div>
  `);
  return { html, filename: `apex-work-receipt-${r.orderNumber}.html` };
}

export interface StatementRow {
  date: string | Date;
  orderNumber: string;
  clientName: string;
  amountEtb: number;
  platformFeeEtb: number;
  sellerNetEtb: number;
}

export interface StatementSummary {
  month: string;
  grossEtb: number;
  feesEtb: number;
  netEtb: number;
  orders: number;
}

/** Build a standalone, printable HTML monthly earnings statement for a seller. */
export function buildMonthlyStatement(month: string, rows: StatementRow[], holder: string): { html: string; filename: string; summary: StatementSummary } {
  const parts = month.split('-');
  const y = parts[0] ? Number(parts[0]) : NaN;
  const m = parts[1] ? Number(parts[1]) : NaN;
  const label = Number.isFinite(y) && Number.isFinite(m)
    ? new Date(Date.UTC(y, (Number.isFinite(m) ? m : 1) - 1, 1)).toLocaleDateString('en-US', { timeZone: 'UTC', year: 'numeric', month: 'long' })
    : month;
  const grossEtb = rows.reduce((s, r) => s + r.amountEtb, 0);
  const feesEtb = rows.reduce((s, r) => s + r.platformFeeEtb, 0);
  const netEtb = rows.reduce((s, r) => s + r.sellerNetEtb, 0);
  const rowHtml = rows.length
    ? rows.map((r) => {
        const d = new Date(r.date);
        const dd = Number.isNaN(d.getTime()) ? String(r.date) : d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
        return `<tr><td>${esc(dd)}</td><td>${esc(r.orderNumber)}</td><td>${esc(r.clientName)}</td><td class="num">${etb(r.amountEtb)}</td><td class="num">${etb(r.platformFeeEtb)}</td><td class="num">${etb(r.sellerNetEtb)}</td></tr>`;
      }).join('')
    : `<tr><td colspan="6" style="text-align:center;padding:20px;color:#9ca3af">No completed orders this month.</td></tr>`;
  const html = doc(`Apex-Work earnings ${month}`, `
    <div class="brand"><span class="dot"></span>Apex-Work</div>
    <h1 class="h1">Monthly earnings statement</h1>
    <div class="sub">${esc(label)} · ${esc(holder)}</div>
    <div class="totals">
      <div class="row"><span>Gross</span><b>${etb(grossEtb)}</b></div>
      <div class="row"><span class="muted">Platform fees</span><span class="muted">− ${etb(feesEtb)}</span></div>
      <div class="row" style="border-bottom:none"><span>Net earnings</span><b>${etb(netEtb)}</b></div>
    </div>
    <div class="sub" style="margin-top:14px">${rows.length} completed order(s) · ${esc(month)}</div>
    <table>
      <thead><tr><th>Date</th><th>Order</th><th>Client</th><th class="num">Gross</th><th class="num">Fees</th><th class="num">Net</th></tr></thead>
      <tbody>${rowHtml}</tbody>
    </table>
  `);
  return {
    html,
    filename: `apex-work-earnings-${month}.html`,
    summary: { month, grossEtb, feesEtb, netEtb, orders: rows.length },
  };
}
